### ISSUE TITLE
发现上拉加载时会多次调用onLoadMore(),上拉加载中状态可以在内部判断.

### ISSUE THREAD

**Issue by FeverCombo3** [CarGuo/CommonRecycler#1]
if(((CommonRecyclerAdapter)recyclerView.getAdapter()).getLoadMoreState() !=LoadMoreHolder.LOADING_STATE){
                onLoadMore();
            }
Holder里加一个加载中的状态，这样在加载中就不会再调用onLoadMore了。

**Comment by CarGuo** [comment]
已经更新3.0新模式，更方便好用😁😁😁
